FROM node:lts-slim AS build
WORKDIR /app
COPY StockExchange.ReactUI/package*.json ./
RUN npm ci --ignore-scripts
COPY StockExchange.ReactUI/. ./
RUN npm run build

FROM nginx:stable AS final
RUN addgroup -S nonroot \
    && adduser -S nonroot -G nonroot
USER nonroot
EXPOSE 80
EXPOSE 443
# 2025/04/21 - Uncomment the line below to replace the default NGINX configuration with your custom one
#COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
