FROM node:lts-slim AS build
WORKDIR /app
#RUN npm install --silent -g @angular/cli
COPY StockExchange.ReactUI/package*.json ./
RUN npm ci
COPY StockExchange.ReactUI/. ./
RUN npm run build

FROM nginx:stable AS final
EXPOSE 80
EXPOSE 443
# 2025/04/21 - Uncomment the line below to replace the default NGINX configuration with your custom one
#COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
