# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  stockexchange.angularui:
    image: stockexchange.angularui
    container_name: stockexchange.angularui
    depends_on:
      - stockexchange.webapi
    build:
      context: .
      dockerfile: ./Dockerfile.angularui
    environment:
      NODE_ENV: development
    ports:
      - 7000:80
      #- 443:443
      #- 9229:9229
    networks:
      - stockexchange
    command: ["node", "--inspect=0.0.0.0:9229", "dist/remapping.umd.js"]

  stockexchange.reactui:
    image: stockexchange.reactui
    container_name: stockexchange.reactui
    depends_on:
      - stockexchange.webapi
    build:
      context: .
      dockerfile: ./Dockerfile.reactui
    environment:
      NODE_ENV: development
    ports:
      - 7100:80
      #- 443:443
      #- 9229:9229
    networks:
      - stockexchange
    command: ["node", "--inspect=0.0.0.0:9229", "dist/remapping.umd.js"]

  stockexchange.webapi:
    image: stockexchange.webapi
    container_name: stockexchange.webapi
    build:
      context: .
      dockerfile: ./Dockerfile.webapi
      args:
        - configuration=Debug
    ports:
      - 7200:80
      #- 443:443
    networks:
      - stockexchange
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    
networks:
  stockexchange:
    driver: bridge
