FROM node:lts-slim AS build
WORKDIR /app
RUN npm i -g --silent --ignore-scripts @angular/cli@21.2.19
COPY StockExchange.AngularUI/package*.json ./
RUN npm ci --ignore-scripts
COPY StockExchange.AngularUI/. ./
RUN ng build --configuration=production

FROM nginx:stable AS final
RUN addgroup -S nonroot \
    && adduser -S nonroot -G nonroot
USER nonroot
EXPOSE 80
EXPOSE 443
# 2025/04/21 - Uncomment the line below to replace the default NGINX configuration with your custom one
#COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/stock-exchange.angular-ui/browser /usr/share/nginx/html
