name: SonarQubeVueUI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  frontend:
    name: Frontend - Vue - Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StockExchange.VueUI

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.0.0'

      - name: Install StockExchange.VueUI Dependencies
        run: npm ci --ignore-scripts

      - name: Build StockExchange.VueUI
        run: npm run build

      - name: Begin Sonar Analysis for StockExchange.VueUI
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
