name: SonarQubeAngularUI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  frontend:
    name: Frontend - Angular - Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StockExchange.AngularUI

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.0.0'

      - name: Install Angular CLI
        run: npm i -g --ignore-scripts @angular/cli@21.2.19

      - name: Install StockExchange.AngularUI Dependencies
        run: npm ci --ignore-scripts

      - name: Build StockExchange.AngularUI
        run: npm exec --ignore-scripts ng build --configuration=production

      - name: Begin Sonar Analysis for StockExchange.AngularUI (v8.2.1)
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
